import React from 'react';
import H from 'next/head'
interface Props {}
export const  Head: React.FC<Props> = ({}) => {
    return (
        <H>
        <title>RAI - React Activity Indicators</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </H>
    );
};